using BlazorBlaze.Server.NativePlayer;
using Bunit;
using Microsoft.Extensions.DependencyInjection;
using ModelingEvolution.EventAggregator;
using NSubstitute;
using EventAggregator = ModelingEvolution.EventAggregator.EventAggregator;

namespace BlazorBlaze.Server.Tests.NativePlayer;

public sealed class VideoSurfaceEventAggregatorTests : BunitContext
{
    private readonly List<PlayerInitialized> _initializedEvents = [];
    private readonly List<PlayerDestroyed> _destroyedEvents = [];
    private readonly BunitJSModuleInterop _moduleInterop;

    private readonly EventAggregator _ea = new(new NullForwarder(), new EventAggregatorPool());

    public VideoSurfaceEventAggregatorTests()
    {
        var kioskDetector = Substitute.For<IKioskDetector>();
        kioskDetector.IsKiosk.Returns(true);
        Services.AddSingleton(kioskDetector);
        Services.AddSingleton<IEventAggregator>(_ea);

        _moduleInterop = JSInterop.SetupModule("./_content/BlazorBlaze.Server/video-surface.js");
        _moduleInterop.Mode = JSRuntimeMode.Loose;

        _ea.GetEvent<PlayerInitialized>().Subscribe(e => _initializedEvents.Add(e));
        _ea.GetEvent<PlayerDestroyed>().Subscribe(e => _destroyedEvents.Add(e));
    }

    [Fact]
    public void KioskMode_PublishesPlayerInitializedOnFirstRender()
    {
        Render<VideoSurface>(p =>
            p.Add(vs => vs.StreamUrl, "http://localhost/stream"));

        _initializedEvents.Should().ContainSingle();
    }

    [Fact]
    public void KioskMode_PlayerInitialized_HasCorrectId()
    {
        Render<VideoSurface>(p => p
            .Add(vs => vs.StreamUrl, "http://localhost/stream")
            .Add(vs => vs.PlayerId, "player-1"));

        _initializedEvents.Should().ContainSingle(e => e.Id == "player-1");
    }

    [Fact]
    public void KioskMode_PlayerInitialized_HasCorrectUrl()
    {
        Render<VideoSurface>(p => p
            .Add(vs => vs.StreamUrl, "http://cam/mjpeg")
            .Add(vs => vs.PlayerId, "player-2"));

        _initializedEvents.Should().ContainSingle(e => e.Url == "http://cam/mjpeg");
    }

    [Fact]
    public void KioskMode_PlayerInitialized_IdIsNotEmpty()
    {
        Render<VideoSurface>(p =>
            p.Add(vs => vs.StreamUrl, "http://localhost/stream"));

        _initializedEvents.Should().ContainSingle();
        _initializedEvents[0].Id.Should().NotBeNullOrEmpty();
    }

    [Fact]
    public void KioskMode_PlayerInitialized_AutoGeneratedIdHasPrefix()
    {
        Render<VideoSurface>(p =>
            p.Add(vs => vs.StreamUrl, "http://localhost/stream"));

        _initializedEvents.Should().ContainSingle();
        _initializedEvents[0].Id.Should().StartWith("vs-");
    }

    [Fact]
    public async Task KioskMode_PublishesPlayerDestroyedOnDispose()
    {
        Render<VideoSurface>(p => p
            .Add(vs => vs.StreamUrl, "http://localhost/stream")
            .Add(vs => vs.PlayerId, "player-dispose"));

        await DisposeComponentsAsync();

        _destroyedEvents.Should().ContainSingle(e => e.Id == "player-dispose");
    }

    [Fact]
    public async Task KioskMode_DestroyedId_MatchesInitializedId()
    {
        Render<VideoSurface>(p =>
            p.Add(vs => vs.StreamUrl, "http://localhost/stream"));

        await DisposeComponentsAsync();

        _initializedEvents.Should().ContainSingle();
        _destroyedEvents.Should().ContainSingle();
        _destroyedEvents[0].Id.Should().Be(_initializedEvents[0].Id);
    }

    [Fact]
    public void KioskMode_TwoInstances_PublishTwoDistinctPlayerInitializedEvents()
    {
        Render<VideoSurface>(p => p
            .Add(vs => vs.StreamUrl, "http://localhost/stream1")
            .Add(vs => vs.PlayerId, "player-a"));

        Render<VideoSurface>(p => p
            .Add(vs => vs.StreamUrl, "http://localhost/stream2")
            .Add(vs => vs.PlayerId, "player-b"));

        _initializedEvents.Should().HaveCount(2);
        _initializedEvents.Select(e => e.Id).Should().BeEquivalentTo(["player-a", "player-b"]);
    }

    [Fact]
    public void KioskMode_PlayerInitialized_CarriesNonZeroRect()
    {
        _moduleInterop.Setup<PlayerRect>("getRect").SetResult(new PlayerRect(10, 20, 1280, 720));

        Render<VideoSurface>(p =>
            p.Add(vs => vs.StreamUrl, "http://localhost/stream"));

        _initializedEvents.Should().ContainSingle();
        var evt = _initializedEvents[0];
        evt.X.Should().Be(10);
        evt.Y.Should().Be(20);
        evt.Width.Should().Be(1280);
        evt.Height.Should().Be(720);
    }

    [Fact]
    public void BrowserMode_DoesNotPublishPlayerInitialized()
    {
        var ctx = new BunitContext();
        var kioskDetector = Substitute.For<IKioskDetector>();
        kioskDetector.IsKiosk.Returns(false);
        ctx.Services.AddSingleton(kioskDetector);
        var browserEa = new EventAggregator(new NullForwarder(), new EventAggregatorPool());
        ctx.Services.AddSingleton<IEventAggregator>(browserEa);

        var browserEvents = new List<PlayerInitialized>();
        browserEa.GetEvent<PlayerInitialized>().Subscribe(e => browserEvents.Add(e));

        ctx.Render<VideoSurface>(p =>
            p.Add(vs => vs.StreamUrl, "http://localhost/stream"));

        browserEvents.Should().BeEmpty();
    }
}
