using BlazorBlaze.Server.NativePlayer;
using Bunit;
using Microsoft.Extensions.DependencyInjection;
using ModelingEvolution.EventAggregator;
using NSubstitute;
using EventAggregator = ModelingEvolution.EventAggregator.EventAggregator;

namespace BlazorBlaze.Server.Tests.NativePlayer;

/// <summary>
/// Tests EA-01 through EA-10: VideoSurface publishes typed IEventAggregator events
/// replacing the deleted INativePlayerRegistry.Register / Unregister calls.
/// Covers Scenario 13 (blazor-blaze side) and the ID-semantics constraint from
/// iter-21 design §7.3 (targeted vs broadcast).
/// </summary>
public sealed class VideoSurfaceEventAggregatorTests : BunitContext
{
    private readonly List<PlayerInitialized> _initializedEvents = [];
    private readonly List<PlayerDestroyed> _destroyedEvents = [];
    private readonly BunitJSModuleInterop _moduleInterop;

    private readonly EventAggregator _ea = new(new NullForwarder(), new EventAggregatorPool());

    public VideoSurfaceEventAggregatorTests()
    {
        var kioskDetector = Substitute.For<IKioskDetector>();
        kioskDetector.IsKiosk.Returns(true);
        Services.AddSingleton(kioskDetector);
        Services.AddSingleton<IEventAggregator>(_ea);

        _moduleInterop = JSInterop.SetupModule("./_content/BlazorBlaze.Server/video-surface.js");
        _moduleInterop.Mode = JSRuntimeMode.Loose;

        _ea.GetEvent<PlayerInitialized>().Subscribe(e => _initializedEvents.Add(e));
        _ea.GetEvent<PlayerDestroyed>().Subscribe(e => _destroyedEvents.Add(e));
    }

    /// <summary>EA-01: PlayerInitialized published exactly once after first render in kiosk mode.</summary>
    [Fact]
    public void KioskMode_PublishesPlayerInitializedOnFirstRender()
    {
        Render<VideoSurface>(p =>
            p.Add(vs => vs.StreamUrl, "http://localhost/stream"));

        _initializedEvents.Should().ContainSingle();
    }

    /// <summary>EA-02: PlayerInitialized carries the correct player ID.</summary>
    [Fact]
    public void KioskMode_PlayerInitialized_HasCorrectId()
    {
        Render<VideoSurface>(p => p
            .Add(vs => vs.StreamUrl, "http://localhost/stream")
            .Add(vs => vs.PlayerId, "player-1"));

        _initializedEvents.Should().ContainSingle(e => e.Id == "player-1");
    }

    /// <summary>EA-03: PlayerInitialized carries the correct stream URL.</summary>
    [Fact]
    public void KioskMode_PlayerInitialized_HasCorrectUrl()
    {
        Render<VideoSurface>(p => p
            .Add(vs => vs.StreamUrl, "http://cam/mjpeg")
            .Add(vs => vs.PlayerId, "player-2"));

        _initializedEvents.Should().ContainSingle(e => e.Url == "http://cam/mjpeg");
    }

    /// <summary>EA-04: PlayerInitialized uses targeted semantics — Id is the player ID, not empty.</summary>
    [Fact]
    public void KioskMode_PlayerInitialized_IdIsNotEmpty()
    {
        Render<VideoSurface>(p =>
            p.Add(vs => vs.StreamUrl, "http://localhost/stream"));

        _initializedEvents.Should().ContainSingle();
        _initializedEvents[0].Id.Should().NotBeNullOrEmpty();
    }

    /// <summary>EA-05: Auto-generated player ID starts with "vs-" prefix.</summary>
    [Fact]
    public void KioskMode_PlayerInitialized_AutoGeneratedIdHasPrefix()
    {
        Render<VideoSurface>(p =>
            p.Add(vs => vs.StreamUrl, "http://localhost/stream"));

        _initializedEvents.Should().ContainSingle();
        _initializedEvents[0].Id.Should().StartWith("vs-");
    }

    /// <summary>EA-06: PlayerDestroyed published on dispose with correct player ID.</summary>
    [Fact]
    public async Task KioskMode_PublishesPlayerDestroyedOnDispose()
    {
        Render<VideoSurface>(p => p
            .Add(vs => vs.StreamUrl, "http://localhost/stream")
            .Add(vs => vs.PlayerId, "player-dispose"));

        await DisposeComponentsAsync();

        _destroyedEvents.Should().ContainSingle(e => e.Id == "player-dispose");
    }

    /// <summary>EA-07: PlayerDestroyed Id matches PlayerInitialized Id for the same component.</summary>
    [Fact]
    public async Task KioskMode_DestroyedId_MatchesInitializedId()
    {
        Render<VideoSurface>(p =>
            p.Add(vs => vs.StreamUrl, "http://localhost/stream"));

        await DisposeComponentsAsync();

        _initializedEvents.Should().ContainSingle();
        _destroyedEvents.Should().ContainSingle();
        _destroyedEvents[0].Id.Should().Be(_initializedEvents[0].Id);
    }

    /// <summary>EA-08: Two VideoSurface instances publish two distinct PlayerInitialized events.</summary>
    [Fact]
    public void KioskMode_TwoInstances_PublishTwoDistinctPlayerInitializedEvents()
    {
        Render<VideoSurface>(p => p
            .Add(vs => vs.StreamUrl, "http://localhost/stream1")
            .Add(vs => vs.PlayerId, "player-a"));

        Render<VideoSurface>(p => p
            .Add(vs => vs.StreamUrl, "http://localhost/stream2")
            .Add(vs => vs.PlayerId, "player-b"));

        _initializedEvents.Should().HaveCount(2);
        _initializedEvents.Select(e => e.Id).Should().BeEquivalentTo(["player-a", "player-b"]);
    }

    /// <summary>EA-09: Browser mode does not publish PlayerInitialized.</summary>
    [Fact]
    public void BrowserMode_DoesNotPublishPlayerInitialized()
    {
        var ctx = new BunitContext();
        var kioskDetector = Substitute.For<IKioskDetector>();
        kioskDetector.IsKiosk.Returns(false);
        ctx.Services.AddSingleton(kioskDetector);
        var browserEa = new EventAggregator(new NullForwarder(), new EventAggregatorPool());
        ctx.Services.AddSingleton<IEventAggregator>(browserEa);

        var browserEvents = new List<PlayerInitialized>();
        browserEa.GetEvent<PlayerInitialized>().Subscribe(e => browserEvents.Add(e));

        ctx.Render<VideoSurface>(p =>
            p.Add(vs => vs.StreamUrl, "http://localhost/stream"));

        browserEvents.Should().BeEmpty();
    }

}
